# This is a basic workflow to help you get started with Actions

name: "Python Wrapper"

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [ 'pull_request' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install Go 1.16
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    # Runs a set of commands using the runners shell
    - name: Build ChevronLib
      run: |
        echo "Running go generate"
        export PATH=$PATH:`go env GOPATH`/bin
        go get -u github.com/go-bindata/go-bindata/...
        go get -u github.com/swaggo/swag/cmd/swag
        go generate ./...

        cd tools/wrappers/
        echo "Building linux chevron.so"
        go build -o chevron.so -buildmode=c-shared
        cd python
        echo "Installing dependencies"
        python3 -m pip install -r requirements.txt
        cp ../chevron.so chevron
    - name: Run PyTest
      run: |
        echo "Running jest"
        cd tools/wrappers/python
        pip3 install pytest-runner==4.4
        pip3 install pytest==4.4.1
        python3 setup.py pytest
